# Generated by Django 2.2.1 on 2019-06-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=8)),
                ('video', models.CharField(max_length=255)),
                ('video_show', models.ImageField(upload_to='')),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255, null=True)),
                ('id_show', models.ImageField(upload_to='')),
                ('order', models.ImageField(upload_to='')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCooperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=20)),
                ('phone', models.ImageField(upload_to='')),
                ('site', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winxi', models.CharField(max_length=255, null=True)),
                ('phone', models.ImageField(upload_to='')),
                ('e_mail', models.CharField(max_length=50, null=True)),
                ('weibo', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorporateCulture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=8)),
                ('title_logo', models.CharField(max_length=255)),
                ('title_logo_show', models.ImageField(upload_to='')),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DevelopmentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=8)),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=255)),
                ('firm_site', models.CharField(max_length=255)),
                ('firm_map', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11)),
                ('logo', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255, null=True)),
                ('Brand_show', models.ImageField(upload_to='')),
                ('order', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ScopeOfService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=8)),
                ('service_url', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=8)),
                ('content', models.CharField(max_length=255, null=True)),
                ('use_place', models.CharField(max_length=8, null=True)),
            ],
        ),
    ]
